# Generated by Django 3.2.7 on 2021-09-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210927_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
